# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "E:/G2_C906/C906_G2/C906_G2.runs/synth_1/c906_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 5
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7k325tffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/G2_C906/C906_G2/C906_G2.cache/wt [current_project]
set_property parent.project_path E:/G2_C906/C906_G2/C906_G2.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:genesys2:part0:1.1 [current_project]
set_property ip_output_repo e:/G2_C906/C906_G2/C906_G2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog {
  E:/G2_C906/gen_rtl/tdt/rtl/top/tdt_dmi_define.h
  E:/G2_C906/gen_rtl/tdt/rtl/top/tdt_define.h
  E:/G2_C906/gen_rtl/mmu/rtl/sysmap.h
  E:/G2_C906/gen_rtl/cpu/rtl/cpu_cfig.h
  E:/G2_C906/gen_rtl/lsu/rtl/aq_lsu_cfig.h
  E:/G2_C906/gen_rtl/idu/rtl/aq_idu_cfig.h
  E:/G2_C906/gen_rtl/dtu/rtl/aq_dtu_cfig.h
}
set_property file_type "Verilog Header" [get_files E:/G2_C906/gen_rtl/tdt/rtl/top/tdt_dmi_define.h]
set_property is_global_include true [get_files E:/G2_C906/gen_rtl/tdt/rtl/top/tdt_dmi_define.h]
set_property file_type "Verilog Header" [get_files E:/G2_C906/gen_rtl/tdt/rtl/top/tdt_define.h]
set_property is_global_include true [get_files E:/G2_C906/gen_rtl/tdt/rtl/top/tdt_define.h]
set_property file_type "Verilog Header" [get_files E:/G2_C906/gen_rtl/mmu/rtl/sysmap.h]
set_property is_global_include true [get_files E:/G2_C906/gen_rtl/mmu/rtl/sysmap.h]
set_property file_type "Verilog Header" [get_files E:/G2_C906/gen_rtl/cpu/rtl/cpu_cfig.h]
set_property is_global_include true [get_files E:/G2_C906/gen_rtl/cpu/rtl/cpu_cfig.h]
set_property file_type "Verilog Header" [get_files E:/G2_C906/gen_rtl/lsu/rtl/aq_lsu_cfig.h]
set_property is_global_include true [get_files E:/G2_C906/gen_rtl/lsu/rtl/aq_lsu_cfig.h]
set_property file_type "Verilog Header" [get_files E:/G2_C906/gen_rtl/idu/rtl/aq_idu_cfig.h]
set_property is_global_include true [get_files E:/G2_C906/gen_rtl/idu/rtl/aq_idu_cfig.h]
set_property file_type "Verilog Header" [get_files E:/G2_C906/gen_rtl/dtu/rtl/aq_dtu_cfig.h]
set_property is_global_include true [get_files E:/G2_C906/gen_rtl/dtu/rtl/aq_dtu_cfig.h]
read_verilog -library xil_defaultlib {
  E:/G2_C906/gen_rtl/common/rtl/BUFGCE.v
  E:/G2_C906/logical/ahb/ahb.v
  E:/G2_C906/logical/ahb/ahb2apb.v
  E:/G2_C906/logical/apb/apb.v
  E:/G2_C906/logical/apb/apb_bridge.v
  E:/G2_C906/gen_rtl/biu/rtl/aq_biu_apbif.v
  E:/G2_C906/gen_rtl/biu/rtl/aq_biu_read_channel.v
  E:/G2_C906/gen_rtl/biu/rtl/aq_biu_req_arbiter.v
  E:/G2_C906/gen_rtl/biu/rtl/aq_biu_top.v
  E:/G2_C906/gen_rtl/biu/rtl/aq_biu_write_channel.v
  E:/G2_C906/gen_rtl/biu/rtl/aq_biu_wt_entry.v
  E:/G2_C906/gen_rtl/cpu/rtl/aq_core.v
  E:/G2_C906/gen_rtl/cp0/rtl/aq_cp0_cache_inst.v
  E:/G2_C906/gen_rtl/cp0/rtl/aq_cp0_ext_csr.v
  E:/G2_C906/gen_rtl/cp0/rtl/aq_cp0_fence_inst.v
  E:/G2_C906/gen_rtl/cp0/rtl/aq_cp0_float_csr.v
  E:/G2_C906/gen_rtl/cp0/rtl/aq_cp0_hpcp_csr.v
  E:/G2_C906/gen_rtl/cp0/rtl/aq_cp0_info_csr.v
  E:/G2_C906/gen_rtl/cp0/rtl/aq_cp0_iui.v
  E:/G2_C906/gen_rtl/cp0/rtl/aq_cp0_lpmd.v
  E:/G2_C906/gen_rtl/cp0/rtl/aq_cp0_prtc_csr.v
  E:/G2_C906/gen_rtl/cp0/rtl/aq_cp0_regs.v
  E:/G2_C906/gen_rtl/cp0/rtl/aq_cp0_rst_ctrl.v
  E:/G2_C906/gen_rtl/cp0/rtl/aq_cp0_special.v
  E:/G2_C906/gen_rtl/cp0/rtl/aq_cp0_top.v
  E:/G2_C906/gen_rtl/cp0/rtl/aq_cp0_trap_csr.v
  E:/G2_C906/gen_rtl/cp0/rtl/aq_cp0_vector_inst.v
  E:/G2_C906/gen_rtl/cpu/rtl/aq_cpuio_top.v
  E:/G2_C906/gen_rtl/lsu/rtl/aq_dcache_data_array.v
  E:/G2_C906/gen_rtl/lsu/rtl/aq_dcache_dirty_array.v
  E:/G2_C906/gen_rtl/lsu/rtl/aq_dcache_tag_array.v
  E:/G2_C906/gen_rtl/lsu/rtl/aq_dcache_top.v
  E:/G2_C906/gen_rtl/dtu/rtl/aq_dtu_cdc.v
  E:/G2_C906/gen_rtl/dtu/rtl/aq_dtu_cdc_lvl.v
  E:/G2_C906/gen_rtl/dtu/rtl/aq_dtu_cdc_pulse.v
  E:/G2_C906/gen_rtl/dtu/rtl/aq_dtu_ctrl.v
  E:/G2_C906/gen_rtl/dtu/rtl/aq_dtu_dbginfo.v
  E:/G2_C906/gen_rtl/dtu/rtl/aq_dtu_iie_trigger.v
  E:/G2_C906/gen_rtl/dtu/rtl/aq_dtu_m_iie_all.v
  E:/G2_C906/gen_rtl/dtu/rtl/aq_dtu_mcontrol.v
  E:/G2_C906/gen_rtl/dtu/rtl/aq_dtu_mcontrol_output_select.v
  E:/G2_C906/gen_rtl/dtu/rtl/aq_dtu_pcfifo.v
  E:/G2_C906/gen_rtl/dtu/rtl/aq_dtu_top.v
  E:/G2_C906/gen_rtl/dtu/rtl/aq_dtu_trigger_module.v
  E:/G2_C906/gen_rtl/fpga/rtl/aq_f_spsram_1024x16.v
  E:/G2_C906/gen_rtl/fpga/rtl/aq_f_spsram_1024x64.v
  E:/G2_C906/gen_rtl/fpga/rtl/aq_f_spsram_128x8.v
  E:/G2_C906/gen_rtl/fpga/rtl/aq_f_spsram_2048x32.v
  E:/G2_C906/gen_rtl/fpga/rtl/aq_f_spsram_256x59.v
  E:/G2_C906/gen_rtl/fpga/rtl/aq_f_spsram_64x58.v
  E:/G2_C906/gen_rtl/fpga/rtl/aq_f_spsram_64x88.v
  E:/G2_C906/gen_rtl/fpga/rtl/aq_f_spsram_64x98.v
  E:/G2_C906/gen_rtl/vfalu/rtl/aq_fadd_double_add.v
  E:/G2_C906/gen_rtl/vfalu/rtl/aq_fadd_double_cmp_max.v
  E:/G2_C906/gen_rtl/vfalu/rtl/aq_fadd_double_dp.v
  E:/G2_C906/gen_rtl/vfalu/rtl/aq_fadd_double_round.v
  E:/G2_C906/gen_rtl/vfalu/rtl/aq_fadd_double_special.v
  E:/G2_C906/gen_rtl/vfalu/rtl/aq_fadd_double_top.v
  E:/G2_C906/gen_rtl/vfalu/rtl/aq_fadd_lop_s1_sb.v
  E:/G2_C906/gen_rtl/vfalu/rtl/aq_fadd_scalar_dp.v
  E:/G2_C906/gen_rtl/vfalu/rtl/aq_fadd_shift_sub_h_double.v
  E:/G2_C906/gen_rtl/vfalu/rtl/aq_fadd_shift_sub_single.v
  E:/G2_C906/gen_rtl/vfalu/rtl/aq_falu_ctrl.v
  E:/G2_C906/gen_rtl/vfalu/rtl/aq_falu_top.v
  E:/G2_C906/gen_rtl/vfalu/rtl/aq_fcnvt_ctrl.v
  E:/G2_C906/gen_rtl/vfalu/rtl/aq_fcnvt_double.v
  E:/G2_C906/gen_rtl/vfalu/rtl/aq_fcnvt_dtos_d.v
  E:/G2_C906/gen_rtl/vfalu/rtl/aq_fcnvt_ftoi_d.v
  E:/G2_C906/gen_rtl/vfalu/rtl/aq_fcnvt_scalar_dp.v
  E:/G2_C906/gen_rtl/vfalu/rtl/aq_fcnvt_top.v
  E:/G2_C906/gen_rtl/vfalu/rtl/aq_fcnvt_xtoh_sh.v
  E:/G2_C906/gen_rtl/vfdsu/rtl/aq_fdsu_denorm_shift.v
  E:/G2_C906/gen_rtl/vfdsu/rtl/aq_fdsu_double.v
  E:/G2_C906/gen_rtl/vfdsu/rtl/aq_fdsu_double_dp.v
  E:/G2_C906/gen_rtl/vfdsu/rtl/aq_fdsu_pack.v
  E:/G2_C906/gen_rtl/vfdsu/rtl/aq_fdsu_prepare.v
  E:/G2_C906/gen_rtl/vfdsu/rtl/aq_fdsu_right_shift.v
  E:/G2_C906/gen_rtl/vfdsu/rtl/aq_fdsu_round.v
  E:/G2_C906/gen_rtl/vfdsu/rtl/aq_fdsu_scalar_ctrl.v
  E:/G2_C906/gen_rtl/vfdsu/rtl/aq_fdsu_scalar_dp.v
  E:/G2_C906/gen_rtl/vfdsu/rtl/aq_fdsu_special.v
  E:/G2_C906/gen_rtl/vfdsu/rtl/aq_fdsu_srt.v
  E:/G2_C906/gen_rtl/vfdsu/rtl/aq_fdsu_top.v
  E:/G2_C906/gen_rtl/vfalu/rtl/aq_fspu_top.v
  E:/G2_C906/gen_rtl/pmu/rtl/aq_hpcp_adder_sel.v
  E:/G2_C906/gen_rtl/pmu/rtl/aq_hpcp_cnt.v
  E:/G2_C906/gen_rtl/pmu/rtl/aq_hpcp_cntinten_reg.v
  E:/G2_C906/gen_rtl/pmu/rtl/aq_hpcp_cntof_reg.v
  E:/G2_C906/gen_rtl/pmu/rtl/aq_hpcp_event.v
  E:/G2_C906/gen_rtl/pmu/rtl/aq_hpcp_top.v
  E:/G2_C906/gen_rtl/idu/rtl/aq_idu_expand_32.v
  E:/G2_C906/gen_rtl/idu/rtl/aq_idu_id_ctrl.v
  E:/G2_C906/gen_rtl/idu/rtl/aq_idu_id_decd.v
  E:/G2_C906/gen_rtl/idu/rtl/aq_idu_id_dp.v
  E:/G2_C906/gen_rtl/idu/rtl/aq_idu_id_gpr.v
  E:/G2_C906/gen_rtl/idu/rtl/aq_idu_id_gpr_gated_reg.v
  E:/G2_C906/gen_rtl/idu/rtl/aq_idu_id_split.v
  E:/G2_C906/gen_rtl/idu/rtl/aq_idu_id_wbt.v
  E:/G2_C906/gen_rtl/idu/rtl/aq_idu_id_wbt_entry.v
  E:/G2_C906/gen_rtl/idu/rtl/aq_idu_top.v
  E:/G2_C906/gen_rtl/ifu/rtl/aq_ifu_bht.v
  E:/G2_C906/gen_rtl/ifu/rtl/aq_ifu_bht_array.v
  E:/G2_C906/gen_rtl/ifu/rtl/aq_ifu_btb.v
  E:/G2_C906/gen_rtl/ifu/rtl/aq_ifu_btb_entry.v
  E:/G2_C906/gen_rtl/ifu/rtl/aq_ifu_ctrl.v
  E:/G2_C906/gen_rtl/ifu/rtl/aq_ifu_ibuf.v
  E:/G2_C906/gen_rtl/ifu/rtl/aq_ifu_ibuf_entry.v
  E:/G2_C906/gen_rtl/ifu/rtl/aq_ifu_ibuf_pop_entry.v
  E:/G2_C906/gen_rtl/ifu/rtl/aq_ifu_icache.v
  E:/G2_C906/gen_rtl/ifu/rtl/aq_ifu_icache_data_array.v
  E:/G2_C906/gen_rtl/ifu/rtl/aq_ifu_icache_tag_array.v
  E:/G2_C906/gen_rtl/ifu/rtl/aq_ifu_ipack.v
  E:/G2_C906/gen_rtl/ifu/rtl/aq_ifu_ipack_entry.v
  E:/G2_C906/gen_rtl/ifu/rtl/aq_ifu_pcgen.v
  E:/G2_C906/gen_rtl/ifu/rtl/aq_ifu_pre_decd.v
  E:/G2_C906/gen_rtl/ifu/rtl/aq_ifu_pred.v
  E:/G2_C906/gen_rtl/ifu/rtl/aq_ifu_ras.v
  E:/G2_C906/gen_rtl/ifu/rtl/aq_ifu_ras_entry.v
  E:/G2_C906/gen_rtl/ifu/rtl/aq_ifu_top.v
  E:/G2_C906/gen_rtl/ifu/rtl/aq_ifu_vec.v
  E:/G2_C906/gen_rtl/iu/rtl/aq_iu_addr_gen.v
  E:/G2_C906/gen_rtl/iu/rtl/aq_iu_alu.v
  E:/G2_C906/gen_rtl/iu/rtl/aq_iu_bju.v
  E:/G2_C906/gen_rtl/iu/rtl/aq_iu_div.v
  E:/G2_C906/gen_rtl/iu/rtl/aq_iu_div_shift2_kernel.v
  E:/G2_C906/gen_rtl/iu/rtl/aq_iu_mul.v
  E:/G2_C906/gen_rtl/iu/rtl/aq_iu_top.v
  E:/G2_C906/gen_rtl/vfalu/rtl/aq_left_shift_64.v
  E:/G2_C906/gen_rtl/lsu/rtl/aq_lsu_ag.v
  E:/G2_C906/gen_rtl/lsu/rtl/aq_lsu_amo_alu.v
  E:/G2_C906/gen_rtl/lsu/rtl/aq_lsu_amr.v
  E:/G2_C906/gen_rtl/lsu/rtl/aq_lsu_arb.v
  E:/G2_C906/gen_rtl/lsu/rtl/aq_lsu_dc.v
  E:/G2_C906/gen_rtl/lsu/rtl/aq_lsu_dtif.v
  E:/G2_C906/gen_rtl/lsu/rtl/aq_lsu_icc.v
  E:/G2_C906/gen_rtl/lsu/rtl/aq_lsu_lfb.v
  E:/G2_C906/gen_rtl/lsu/rtl/aq_lsu_lfb_entry.v
  E:/G2_C906/gen_rtl/lsu/rtl/aq_lsu_lm.v
  E:/G2_C906/gen_rtl/lsu/rtl/aq_lsu_mcic.v
  E:/G2_C906/gen_rtl/lsu/rtl/aq_lsu_pfb.v
  E:/G2_C906/gen_rtl/lsu/rtl/aq_lsu_pfb_top.v
  E:/G2_C906/gen_rtl/lsu/rtl/aq_lsu_rdl.v
  E:/G2_C906/gen_rtl/lsu/rtl/aq_lsu_stb.v
  E:/G2_C906/gen_rtl/lsu/rtl/aq_lsu_stb_entry.v
  E:/G2_C906/gen_rtl/lsu/rtl/aq_lsu_top.v
  E:/G2_C906/gen_rtl/lsu/rtl/aq_lsu_vb.v
  E:/G2_C906/gen_rtl/mmu/rtl/aq_mmu_arb.v
  E:/G2_C906/gen_rtl/mmu/rtl/aq_mmu_jtlb.v
  E:/G2_C906/gen_rtl/mmu/rtl/aq_mmu_jtlb_data_array.v
  E:/G2_C906/gen_rtl/mmu/rtl/aq_mmu_jtlb_tag_array.v
  E:/G2_C906/gen_rtl/mmu/rtl/aq_mmu_plru.v
  E:/G2_C906/gen_rtl/mmu/rtl/aq_mmu_ptw.v
  E:/G2_C906/gen_rtl/mmu/rtl/aq_mmu_regs.v
  E:/G2_C906/gen_rtl/mmu/rtl/aq_mmu_sysmap.v
  E:/G2_C906/gen_rtl/mmu/rtl/aq_mmu_sysmap_hit.v
  E:/G2_C906/gen_rtl/mmu/rtl/aq_mmu_tlboper.v
  E:/G2_C906/gen_rtl/mmu/rtl/aq_mmu_top.v
  E:/G2_C906/gen_rtl/mmu/rtl/aq_mmu_utlb.v
  E:/G2_C906/gen_rtl/mmu/rtl/aq_mmu_utlb_entry.v
  E:/G2_C906/gen_rtl/mmu/rtl/aq_mmu_utlb_top.v
  E:/G2_C906/gen_rtl/clk/rtl/aq_mp_clk_top.v
  E:/G2_C906/gen_rtl/rst/rtl/aq_mp_rst_top.v
  E:/G2_C906/gen_rtl/pmp/rtl/aq_pmp_acc.v
  E:/G2_C906/gen_rtl/pmp/rtl/aq_pmp_comp_hit.v
  E:/G2_C906/gen_rtl/pmp/rtl/aq_pmp_regs.v
  E:/G2_C906/gen_rtl/pmp/rtl/aq_pmp_top.v
  E:/G2_C906/gen_rtl/lsu/rtl/aq_prio.v
  E:/G2_C906/gen_rtl/rtu/rtl/aq_rtu_ctrl.v
  E:/G2_C906/gen_rtl/rtu/rtl/aq_rtu_dp.v
  E:/G2_C906/gen_rtl/rtu/rtl/aq_rtu_int.v
  E:/G2_C906/gen_rtl/rtu/rtl/aq_rtu_rbus.v
  E:/G2_C906/gen_rtl/rtu/rtl/aq_rtu_retire.v
  E:/G2_C906/gen_rtl/rtu/rtl/aq_rtu_top.v
  E:/G2_C906/gen_rtl/rtu/rtl/aq_rtu_wb.v
  E:/G2_C906/gen_rtl/ifu/rtl/aq_spsram_1024x16.v
  E:/G2_C906/gen_rtl/lsu/rtl/aq_spsram_1024x64.v
  E:/G2_C906/gen_rtl/lsu/rtl/aq_spsram_128x8.v
  E:/G2_C906/gen_rtl/ifu/rtl/aq_spsram_2048x32.v
  E:/G2_C906/gen_rtl/ifu/rtl/aq_spsram_256x59.v
  E:/G2_C906/gen_rtl/lsu/rtl/aq_spsram_64x58.v
  E:/G2_C906/gen_rtl/mmu/rtl/aq_spsram_64x88.v
  E:/G2_C906/gen_rtl/mmu/rtl/aq_spsram_64x98.v
  E:/G2_C906/gen_rtl/cpu/rtl/aq_sysio_kid.v
  E:/G2_C906/gen_rtl/cpu/rtl/aq_sysio_top.v
  E:/G2_C906/gen_rtl/cpu/rtl/aq_top.v
  E:/G2_C906/gen_rtl/vfalu/rtl/aq_vdsp_64_bit_ff1.v
  E:/G2_C906/gen_rtl/vdiv/rtl/aq_vdsp_8_bit_ff1.v
  E:/G2_C906/gen_rtl/vfmau/rtl/aq_vfmau_ctrl.v
  E:/G2_C906/gen_rtl/vfmau/rtl/aq_vfmau_dp.v
  E:/G2_C906/gen_rtl/vfmau/rtl/aq_vfmau_frac_mult.v
  E:/G2_C906/gen_rtl/vfmau/rtl/aq_vfmau_frac_shift_double.v
  E:/G2_C906/gen_rtl/vfmau/rtl/aq_vfmau_lza_double.v
  E:/G2_C906/gen_rtl/vfmau/rtl/aq_vfmau_mult.v
  E:/G2_C906/gen_rtl/vfmau/rtl/aq_vfmau_mult_double.v
  E:/G2_C906/gen_rtl/vfmau/rtl/aq_vfmau_multiplier_53x27_partial.v
  E:/G2_C906/gen_rtl/vfmau/rtl/aq_vfmau_special_judge_double.v
  E:/G2_C906/gen_rtl/vfmau/rtl/aq_vfmau_top.v
  E:/G2_C906/gen_rtl/vidu/rtl/aq_vidu_top.v
  E:/G2_C906/gen_rtl/vidu/rtl/aq_vidu_vid_ctrl_fp.v
  E:/G2_C906/gen_rtl/vidu/rtl/aq_vidu_vid_dp_fp.v
  E:/G2_C906/gen_rtl/vidu/rtl/aq_vidu_vid_gpr_fp.v
  E:/G2_C906/gen_rtl/vidu/rtl/aq_vidu_vid_gpr_reg_fp.v
  E:/G2_C906/gen_rtl/vidu/rtl/aq_vidu_vid_split_fp.v
  E:/G2_C906/gen_rtl/vidu/rtl/aq_vidu_vid_wbt.v
  E:/G2_C906/gen_rtl/vidu/rtl/aq_vidu_vid_wbt_entry.v
  E:/G2_C906/gen_rtl/lsu/rtl/aq_vlsu_data_trans.v
  E:/G2_C906/gen_rtl/lsu/rtl/aq_vlsu_ld_align_buffer.v
  E:/G2_C906/gen_rtl/lsu/rtl/aq_vlsu_lsu_if.v
  E:/G2_C906/gen_rtl/lsu/rtl/aq_vlsu_rot_data.v
  E:/G2_C906/gen_rtl/lsu/rtl/aq_vlsu_st_align_buffer.v
  E:/G2_C906/gen_rtl/lsu/rtl/aq_vlsu_top.v
  E:/G2_C906/gen_rtl/lsu/rtl/aq_vlsu_vtb.v
  E:/G2_C906/gen_rtl/lsu/rtl/aq_vlsu_vtb_entry.v
  E:/G2_C906/gen_rtl/vdsp/rtl/aq_vpu_fwd_wb_rbus.v
  E:/G2_C906/gen_rtl/vdsp/rtl/aq_vpu_group_unit.v
  E:/G2_C906/gen_rtl/vdsp/rtl/aq_vpu_srcv_type.v
  E:/G2_C906/gen_rtl/vdsp/rtl/aq_vpu_top.v
  E:/G2_C906/gen_rtl/vdsp/rtl/aq_vpu_viq_dp.v
  E:/G2_C906/logical/axi/axi2ahb.v
  E:/G2_C906/logical/axi/axi_err128.v
  E:/G2_C906/logical/axi/axi_fifo.v
  E:/G2_C906/logical/axi/axi_fifo_entry.v
  E:/G2_C906/logical/axi/axi_interconnect128.v
  E:/G2_C906/logical/axi/axi_slave128.v
  E:/G2_C906/gen_rtl/iu/rtl/booth_code_33_bit.v
  E:/G2_C906/gen_rtl/vfmau/rtl/booth_code_54_bit.v
  E:/G2_C906/logical/bus/bus_delay.v
  E:/G2_C906/gen_rtl/clint/rtl/clint_func.v
  E:/G2_C906/gen_rtl/clint/rtl/clint_top.v
  E:/G2_C906/logical/common/cpu_sub_system_axi.v
  E:/G2_C906/gen_rtl/plic/rtl/csky_apb_1tox_matrix.v
  E:/G2_C906/logical/common/err_gen.v
  E:/G2_C906/logical/mem/f_spsram_32768x128.v
  E:/G2_C906/logical/mem/f_spsram_524288x128.v
  E:/G2_C906/logical/common/fifo_counter.v
  E:/G2_C906/logical/clk/fpga_clk_gen.v
  E:/G2_C906/gen_rtl/fpga/rtl/fpga_ram.v
  E:/G2_C906/gen_rtl/clk/rtl/gated_clk_cell.v
  E:/G2_C906/logical/gpio/gpio.v
  E:/G2_C906/logical/gpio/gpio_apbif.v
  E:/G2_C906/logical/gpio/gpio_ctrl.v
  E:/G2_C906/logical/mem/mem_ctrl.v
  E:/G2_C906/gen_rtl/iu/rtl/multiplier_33x33_partial.v
  E:/G2_C906/gen_rtl/cpu/rtl/openC906.v
  E:/G2_C906/gen_rtl/plic/rtl/plic_32to1_arb.v
  E:/G2_C906/gen_rtl/plic/rtl/plic_arb_ctrl.v
  E:/G2_C906/gen_rtl/plic/rtl/plic_ctrl.v
  E:/G2_C906/gen_rtl/plic/rtl/plic_granu2_arb.v
  E:/G2_C906/gen_rtl/plic/rtl/plic_granu_arb.v
  E:/G2_C906/gen_rtl/plic/rtl/plic_hart_arb.v
  E:/G2_C906/gen_rtl/plic/rtl/plic_hreg_busif.v
  E:/G2_C906/gen_rtl/plic/rtl/plic_int_kid.v
  E:/G2_C906/gen_rtl/plic/rtl/plic_kid_busif.v
  E:/G2_C906/gen_rtl/plic/rtl/plic_top.v
  E:/G2_C906/logical/mem/ram.v
  E:/G2_C906/logical/common/soc.v
  E:/G2_C906/gen_rtl/common/rtl/sync_level2level.v
  E:/G2_C906/gen_rtl/tdt/rtl/debug/tdt_apb_master.v
  E:/G2_C906/gen_rtl/tdt/rtl/debug/tdt_dm.v
  E:/G2_C906/gen_rtl/tdt/rtl/debug/tdt_dm_pulse_sync.v
  E:/G2_C906/gen_rtl/tdt/rtl/debug/tdt_dm_sync_dff.v
  E:/G2_C906/gen_rtl/tdt/rtl/top/tdt_dm_top.v
  E:/G2_C906/gen_rtl/tdt/rtl/top/tdt_dmi.v
  E:/G2_C906/gen_rtl/tdt/rtl/debug/tdt_dmi_pulse_sync.v
  E:/G2_C906/gen_rtl/tdt/rtl/top/tdt_dmi_rst_top.v
  E:/G2_C906/gen_rtl/tdt/rtl/debug/tdt_dmi_sync_dff.v
  E:/G2_C906/gen_rtl/tdt/rtl/top/tdt_dmi_top.v
  E:/G2_C906/gen_rtl/tdt/rtl/debug/tdt_dtm_chain.v
  E:/G2_C906/gen_rtl/tdt/rtl/debug/tdt_dtm_ctrl.v
  E:/G2_C906/gen_rtl/tdt/rtl/debug/tdt_dtm_idr.v
  E:/G2_C906/gen_rtl/tdt/rtl/debug/tdt_dtm_io.v
  E:/G2_C906/gen_rtl/tdt/rtl/debug/tdt_dtm_top.v
  E:/G2_C906/gen_rtl/tdt/rtl/common/tdt_gated_clk_cell.v
  E:/G2_C906/gen_rtl/tdt/rtl/debug/tdt_sba_axi.v
  E:/G2_C906/gen_rtl/tdt/rtl/top/tdt_top.v
  E:/G2_C906/logical/common/timer.v
  E:/G2_C906/logical/common/tr_axi_interconnect.v
  E:/G2_C906/logical/uart/uart.v
  E:/G2_C906/logical/uart/uart_apb_reg.v
  E:/G2_C906/logical/uart/uart_baud_gen.v
  E:/G2_C906/logical/uart/uart_ctrl.v
  E:/G2_C906/logical/uart/uart_receive.v
  E:/G2_C906/logical/uart/uart_trans.v
  E:/G2_C906/logical/common/wid_entry.v
  E:/G2_C906/C906_G2/C906_G2.srcs/sources_1/new/c906_top.v
}
read_ip -quiet e:/G2_C906/C906_G2/C906_G2.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all e:/G2_C906/C906_G2/C906_G2.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/G2_C906/C906_G2/C906_G2.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all e:/G2_C906/C906_G2/C906_G2.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/G2_C906/C906_G2/C906_G2.srcs/constrs_1/new/G2_c906.xdc
set_property used_in_implementation false [get_files E:/G2_C906/C906_G2/C906_G2.srcs/constrs_1/new/G2_c906.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top c906_top -part xc7k325tffg900-2
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef c906_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file c906_top_utilization_synth.rpt -pb c906_top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
